### ISSUE TITLE
Flickering when using arrows to navigate between screens

### ISSUE THREAD

**Issue by shkfnly** [goshakkk/react-native-simple-onboarding#1]
Hey there is a flicker happening when using the arrows provided. Any thoughts on why?

**Comment by goshacmd** [comment]
Hey, I don't have time to debug this for now. If you feel like it, go ahead and get to the root of it 😉

**Comment by dondragon2** [comment]
was this ever resolved?

**Comment by jjingrong** [comment]
Hey guys (and @shkfnly),

Just did up a bug fix for this on #9. It's caused by calling `this.setState` before `onScroll` has finished running
